[build-system]
requires = [
    "setuptools>=47",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
markers = [
    "smoke: quick test of system health check",
    "get",
]